### ISSUE TITLE
Browser keeps showing parsing error: unexpected token

### ISSUE THREAD

**Issue by zhongh** [zhonghao1014/dcoExpertiseWordCloud#1]
The error is:
"Uncaught SyntaxError: Unexpected token :"
and it points to the second line in query results:
"...  "head": {..."

the main html code is index.html (line 42-ish)

**Comment by zednis** [comment]
I ran the code locally with some updated logging of the error thrown and this is what I got:

```
Error: jQuery214027125416160561144_1437666847951 was not called
    at Function.jQuery.extend.error (http://localhost/~szednik/hao-wordcloud/jquery-2.1.4.js:250:9)
    at jQuery.ajaxPrefilter.s.converters.script json (http://localhost/~szednik/hao-wordcloud/jquery-2.1.4.js:8752:12)
    at ajaxConvert (http://localhost/~szednik/hao-wordcloud/jquery-2.1.4.js:7799:19)
    at done (http://localhost/~szednik/hao-wordcloud/jquery-2.1.4.js:8215:15)
    at HTMLScriptElement.jQuery.ajaxTransport.send.jQuery.prop.on.callback (http://localhost/~szednik/hao-wordcloud/jquery-2.1.4.js:8694:8)
    at HTMLScriptElement.jQuery.event.dispatch (http://localhost/~szednik/hao-wordcloud/jquery-2.1.4.js:4435:9)
    at HTMLScriptElement.jQuery.event.add.elemData.handle (http://localhost/~szednik/hao-wordcloud/jquery-2.1.4.js:4121:28)
```

I am not convinced that VIVO is handling the JSONP request from the server-side.

**Comment by zednis** [comment]
One option I will be looking into is updating our apache configuration to support CORS so we don't have to attempt JSONP.

**Comment by zednis** [comment]
I have updated the CORS configuration on deepcarbon.  Try again with a regular JSON request.

**Comment by stephentmoon** [comment]
It works! Thank you! I'll get started on parsing the results now so we can
put them into the pie chart.

On Thu, Jul 23, 2015 at 1:30 PM, Stephan Zednik notifications@github.com
wrote:

> I have updated the CORS configuration on deepcarbon. Try again with a
> regular JSON request.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zhonghao1014/dcoExpertiseWordCloud/issues/1#issuecomment-124175295
> .

## 

Stephen T. Moon
(860) 480-8751

**Comment by zednis** [comment]
:+1:
